services:
  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CLUSTER_ID: "Q1JGH9yrTNKVouGFe0tRIQ"
    ports:
      - "9092:9092"
    networks:
      - ai-part

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: agent_service
    environment:
      - AGENT_ID=A
      - PORT=3000
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=agent-client
      - KAFKA_CONSUMER_GROUP=agent-group
    networks:
      - ai-part
    ports:
      - "3000:3000"    

  process:
    build:
      context: ./process
      dockerfile: Dockerfile
    container_name: process_service
    environment:
      - AGENT_SERVICE=http://agent:3000
      - DATABASE_URI=mongodb://mongo:27017/sensors
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=process-group
    networks:
      - ai-part
    ports:
      - "5000:5000"
    depends_on:
      - agent
      - redis
      - mongodb
      - kafka

  redis:
    image: redis:8.4.0
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - ai-part

  mongodb:
    image: mongo:8.2
    container_name: mongo
    ports:
      - "27018:27017"
    networks:
      - ai-part
    volumes:
      - mongo_data:/data/db

networks:
  ai-part:

volumes:
  mongo_data:
